/**
 * Build a self-contained SAS program that recreates the Gold Case A fixture,
 * so the emitted SAS twin can actually be RUN.
 *
 * WHY THIS EXISTS. The SAS half of this project has never been executed. Not
 * once. There is no SAS runtime in this repo and no dependency on one: the twin
 * is parity-checked (values scraped from its own emitted text) and structurally
 * linted (balanced comments, closed procs, defined macros). That catches the two
 * twins drifting apart. It cannot catch SAS that does not run, and the repo has
 * already proved the risk is real: the fills twin was reading a `020_rx` table
 * no emitter creates anywhere and would have died on its first statement. Parity
 * did not catch it. A human reading the code did.
 *
 * SAS OnDemand for Academics is free, so the only thing standing between this
 * project and its first executed SAS program is the data. This generates it.
 *
 * DERIVED, NEVER TRANSCRIBED. The rows are read back out of the same PGlite
 * database the harness executes against, so the SAS fixture and the SQL fixture
 * are the same twelve patients by construction. Hand-copying them into DATALINES
 * would create exactly the drift this project keeps finding in other people's
 * work: two lists of the same thing, maintained separately.
 *
 * THE YEARLY SPLIT IS THE INTERESTING PART. Postgres gets one `ccaed_all`. The
 * SAS twin resolves `%tab_d(2018)` to `raw.ccaed181` and loops the year range,
 * so the loader has to split each table by its own date column and emit one data
 * set per family per year. Years with no rows still need an EMPTY data set,
 * because `proc append` against a non-existent base is a hard error and the loop
 * does not know which years are populated. A loader that only wrote populated
 * years would fail on the first sparse family and look like an emitter bug.
 *
 * Run: npm run sas:fixture -w @heor-studio/core
 */
import { PGlite } from "@electric-sql/pglite";
import * as fs from "node:fs";
import * as path from "node:path";
import * as url from "node:url";
import { FIXTURE_DDL, fixtureSeedSql, EXPECTED, GOLD_A_SPEC, GOLD_A_OPTS } from "./fixture";
import { emitSas } from "../emitters/sas";

/** Postgres source table -> (SAS family letter, the date column that dates a row). */
const FAMILIES: Array<{ table: string; letter: string; dateCol: string; label: string }> = [
  { table: "ccaet_all", letter: "t", dateCol: "dtstart", label: "enrollment detail" },
  { table: "ccaed_all", letter: "d", dateCol: "svcdate", label: "outpatient pharmacy claims" },
  { table: "ccaeo_all", letter: "o", dateCol: "svcdate", label: "outpatient services" },
  { table: "ccaes_all", letter: "s", dateCol: "svcdate", label: "inpatient services" },
  { table: "ccaei_all", letter: "i", dateCol: "admdate", label: "inpatient admissions" },
];

type Row = Record<string, unknown>;

/** SAS date literal, or . for missing. Dates arrive from PGlite as Date. */
function sasDate(v: unknown): string {
  if (v === null || v === undefined) return ".";
  const d = v instanceof Date ? v : new Date(String(v));
  if (Number.isNaN(d.getTime())) return ".";
  const MON = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
  const dd = String(d.getUTCDate()).padStart(2, "0");
  return `'${dd}${MON[d.getUTCMonth()]}${d.getUTCFullYear()}'d`;
}

function isDateCol(name: string): boolean {
  return /^(dtstart|dtend|svcdate|admdate|disdate)$/i.test(name);
}

/** A DATALINES value. Delimiter is a bar, because costs and names both appear. */
function cell(name: string, v: unknown): string {
  if (v === null || v === undefined) return ".";
  if (isDateCol(name)) {
    const lit = sasDate(v);
    return lit === "." ? "." : lit.slice(1, -2); // bare DDMMMYYYY for the informat
  }
  return String(v).trim() === "" ? "." : String(v).trim();
}

async function main() {
  const db = new PGlite();
  await db.exec(FIXTURE_DDL);
  await db.exec(fixtureSeedSql());

  /* The year span the SAS loop will walk. Read from the EMITTED setup program
   * rather than assumed, so a spec whose ascertainment window widens cannot
   * leave the loader writing a range the twin does not read. */
  const setup = emitSas(GOLD_A_SPEC, GOLD_A_OPTS).find((f) => f.path.includes("00_setup"))!.content;
  const startYear = Number(/%let start_year\s*=\s*(\d{4})/.exec(setup)?.[1]);
  const endYear = Number(/%let end_year\s*=\s*(\d{4})/.exec(setup)?.[1]);
  if (!startYear || !endYear) throw new Error("could not read start_year/end_year out of the emitted 00_setup.sas");

  const L: string[] = [];
  const P = (s = "") => L.push(s);

  P("/*=============================================================================");
  P("| HEOR Studio — Gold Case A fixture, as SAS data sets");
  P("|");
  P("| GENERATED by packages/core/src/verify/sas-fixture.ts. Do not hand-edit: the");
  P("| rows are read out of the same PGlite database the harness executes the");
  P("| emitted SQL against, so these twelve patients and those twelve patients are");
  P("| the same twelve patients by construction.");
  P("|");
  P("| PURPOSE. The SAS twin has never been executed. Run this first, then run the");
  P("| emitted programs 00 through 360 in order, then compare what they print");
  P("| against SAS-COMPARISON.md, which carries the values Postgres produced from");
  P("| the same rows.");
  P("|");
  P("| SAS OnDemand for Academics (free) is enough. No MarketScan licence is");
  P("| involved: every row below is synthetic and was written by hand to exercise");
  P("| a specific rule.");
  P("|");
  P("| WHAT TO DO WITH A DISAGREEMENT. A difference here is a FINDING, not a");
  P("| nuisance. The SQL side is executed against ground truth derived by hand as");
  P("| exact fractions before anything ran, so if SAS says something else, either");
  P("| the SAS twin is wrong or the derivation is. Both have happened.");
  P("=============================================================================*/");
  P();
  P("/*-- EDIT: point this at a folder you can write to. On SAS OnDemand for");
  P("    Academics, /home/<your-user>/heor is a good choice. This must match the");
  P("    `raw` libname in the emitted 00_setup.sas. --------------------------*/");
  P('%let fixture_out = /home/u00000000/heor;');
  P();
  P('libname raw "&fixture_out.";');
  P();
  P("options nocenter;");
  P();

  let totalRows = 0;
  let emptyDatasets = 0;

  for (const fam of FAMILIES) {
    const all = (await db.query<Row>(`SELECT * FROM ${fam.table}`)).rows;
    const cols = all.length > 0 ? Object.keys(all[0]) : [];
    if (cols.length === 0) throw new Error(`${fam.table} produced no columns`);

    P("/*---------------------------------------------------------------------------");
    P(`  ${fam.table}  ->  raw.ccae${fam.letter}YY1   (${fam.label})`);
    P(`  ${all.length} row(s), split by ${fam.dateCol} across ${startYear}-${endYear}.`);
    P("---------------------------------------------------------------------------*/");

    for (let yr = startYear; yr <= endYear; yr++) {
      const yy = String(yr).slice(2);
      const ds = `raw.ccae${fam.letter}${yy}1`;
      const mine = all.filter((r) => {
        const v = r[fam.dateCol];
        if (v === null || v === undefined) return false;
        const d = v instanceof Date ? v : new Date(String(v));
        return d.getUTCFullYear() === yr;
      });

      /* LENGTH + INFORMAT before INPUT: without an explicit length SAS takes the
       * width of the first value it sees, so a code list whose first ICD code is
       * short silently truncates every longer one after it. That is a wrong
       * answer, not an error. */
      P();
      P(`data ${ds};`);
      P(`  length ${cols.map((c) => (isDateCol(c) ? `${c} 8` : /^(enrolid|caseid)$/i.test(c) ? `${c} 8` : /^(age|dobyr|daysupp|los)$/i.test(c) ? `${c} 8` : /^(qty|paytot|netpay|copay|deduct|coins)$/i.test(c) ? `${c} 8` : `${c} $20`)).join(" ")};`);
      const informats = cols.filter(isDateCol).map((c) => `${c} date9.`);
      if (informats.length > 0) P(`  informat ${informats.join(" ")};`);
      const formats = cols.filter(isDateCol).map((c) => `${c} date9.`);
      if (formats.length > 0) P(`  format ${formats.join(" ")};`);
      P(`  infile datalines dlm='|' dsd missover;`);
      P(`  input ${cols.map((c) => (/^(enrolid|caseid|age|dobyr|daysupp|los|qty|paytot|netpay|copay|deduct|coins)$/i.test(c) || isDateCol(c) ? c : `${c} $`)).join(" ")};`);
      P("datalines;");
      for (const r of mine) P(cols.map((c) => cell(c, r[c])).join("|"));
      P(";");
      P("run;");
      totalRows += mine.length;
      if (mine.length === 0) {
        emptyDatasets++;
        P(`/* EMPTY BY DESIGN. ${fam.label} has no ${yr} rows. The data set still has to`);
        P(`   exist: the twin's %do yr loop appends every year in the range, and`);
        P(`   proc append against a base that is not there is a hard error. */`);
      }
    }
    P();
  }

  /* redbook is not yearly. */
  const rb = (await db.query<Row>("SELECT * FROM redbook")).rows;
  const rbCols = Object.keys(rb[0] ?? { ndcnum: "", gennme: "", prodnme: "" });
  P("/*---------------------------------------------------------------------------");
  P(`  redbook -> raw.redbook   (NDC reference; ${rb.length} rows, not year-split)`);
  P("---------------------------------------------------------------------------*/");
  P("data raw.redbook;");
  P(`  length ${rbCols.map((c) => `${c} $40`).join(" ")};`);
  P("  infile datalines dlm='|' dsd missover;");
  P(`  input ${rbCols.map((c) => `${c} $`).join(" ")};`);
  P("datalines;");
  for (const r of rb) P(rbCols.map((c) => cell(c, r[c])).join("|"));
  P(";");
  P("run;");
  totalRows += rb.length;
  P();
  P("/*-------------------- what landed ------------------------------------------*/");
  P("title 'Fixture load: row counts by data set';");
  P("proc sql;");
  P("  select memname, nobs from dictionary.tables");
  P("  where libname = 'RAW' order by memname;");
  P("quit;");
  P("title;");
  P();
  P("/* NEXT: set `libname raw` in the emitted 00_setup.sas to &fixture_out., leave");
  P("   %let prefix = ccae and %let rel = 1 as they are, then run 00 through 360 in");
  P("   order. Compare against SAS-COMPARISON.md. */");

  const here = path.dirname(url.fileURLToPath(import.meta.url));
  const outDir = path.resolve(here, "../../../../sas-execution");
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, "00_fixture.sas");
  fs.writeFileSync(outFile, L.join("\n") + "\n");

  console.log(`wrote ${outFile}`);
  console.log(`  ${totalRows} rows across ${FAMILIES.length} families + redbook`);
  console.log(`  ${emptyDatasets} empty-by-design data sets (years with no rows)`);
  console.log(`  year range ${startYear}-${endYear}, read from the emitted 00_setup.sas`);

  writeComparison(outDir);
  await db.close();
}

/** The sheet a human diffs SAS output against. Values come from EXPECTED, which
 *  is what the executed SQL is checked against, so this is not a third list. */
function writeComparison(outDir: string) {
  const E = EXPECTED as Record<string, unknown>;
  const fmt = (v: unknown): string =>
    Array.isArray(v) ? `${v.length} patients: ${v.join(", ")}`
      : v === null ? "NULL"
      : typeof v === "object" ? "```" + JSON.stringify(v) + "```"
      : String(v);

  const M: string[] = [];
  M.push("# Gold Case A: what Postgres produced, for diffing against SAS");
  M.push("");
  M.push("Generated by `packages/core/src/verify/sas-fixture.ts` from `EXPECTED` in");
  M.push("`verify/fixture.ts`, which is the same object the executed SQL is checked");
  M.push("against. This is not a third list of the numbers; it is a view of the one the");
  M.push("harness already uses.");
  M.push("");
  M.push("Every value below was derived BY HAND as an exact fraction before any code ran,");
  M.push("then confirmed by executing the emitted SQL in Postgres 16. Where a hand");
  M.push("derivation and an execution disagreed, both were recomputed independently. That");
  M.push("happened, and the execution was right: six 30-day fills at days 0, 30, 60 tile");
  M.push("exactly rather than overlapping, so a fourth patient had PDC equal to MPR.");
  M.push("");
  M.push("## How to use this");
  M.push("");
  M.push("1. Run `00_fixture.sas` on SAS OnDemand for Academics (free).");
  M.push("2. Point `libname raw` in the emitted `00_setup.sas` at the same folder.");
  M.push("3. Run `00_setup.sas` through `360_suppression.sas` in numeric order.");
  M.push("4. Compare each program's printed output against the rows below.");
  M.push("");
  M.push("**A disagreement is a finding.** The SQL side is executed against hand-derived");
  M.push("truth, so if SAS says something else, either the SAS twin is wrong or the");
  M.push("derivation is. Do not adjust one to match the other without working out which.");
  M.push("");
  M.push("**A program that does not RUN is the more likely outcome and the more valuable");
  M.push("one.** Nothing here has ever executed SAS. Record the log, not just the result.");
  M.push("");
  M.push("## Expected values");
  M.push("");
  M.push("| quantity | Postgres value | what SAS should print |");
  M.push("|---|---|---|");
  for (const [k, v] of Object.entries(E)) {
    if (typeof v === "function") continue;
    M.push(`| \`${k}\` | ${fmt(v)} | |`);
  }
  M.push("");
  M.push("## Record the outcome");
  M.push("");
  M.push("For each program, one of: **ran and matched**, **ran and differed** (say how),");
  M.push("or **did not run** (paste the SAS log line). The third is the one worth having");
  M.push("first, because it is the failure mode parity checking structurally cannot see.");
  M.push("");
  M.push("| program | ran? | matched? | note |");
  M.push("|---|---|---|---|");
  const sasFiles = emitSas(GOLD_A_SPEC, GOLD_A_OPTS).map((f) => f.path.replace(/^sas\//, ""));
  for (const f of sasFiles) M.push(`| \`${f}\` | | | |`);
  M.push("");

  const out = path.join(outDir, "SAS-COMPARISON.md");
  fs.writeFileSync(out, M.join("\n") + "\n");
  console.log(`wrote ${out}`);
  console.log(`  ${Object.keys(E).length} expected quantities, ${sasFiles.length} programs to log`);
}

main().catch((e) => { console.error("crashed:", e); process.exit(1); });
