/**
 * Export bundle assembly: spec + generated code + codelists + provenance docs,
 * zipped client-side and delivered via a blob download. Nothing leaves the browser.
 */
import JSZip from "jszip";
import type { CodeList, StudySpec } from "@heor-studio/core";
import { specReadiness, unreviewedCriteria, unverifiedCodeCount } from "@heor-studio/core";
import type { EmitOptions, GeneratedFile } from "@heor-studio/core";
import { emitSas } from "@heor-studio/core";
import { emitSql } from "@heor-studio/core";

export interface BundleEntry {
  path: string;
  content: string;
}

const DB_LABELS: Record<string, string> = {
  marketscan_ccae: "MarketScan Commercial (CCAE)",
  marketscan_mdcr: "MarketScan Medicare Supplemental (MDCR)",
  marketscan_medicaid: "MarketScan Medicaid (MDCD)",
};

/* ---------- csv ---------- */

function csvCell(v: string): string {
  return /[",\n\r]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

function codeListCsv(cl: CodeList): string {
  const lines = ["code,description,system,source,verified"];
  for (const c of cl.codes) {
    lines.push(
      [c.code, c.description ?? "", cl.system, c.source, String(c.verified)]
        .map(csvCell)
        .join(","),
    );
  }
  return lines.join("\r\n") + "\r\n";
}

/* ---------- docs ---------- */

function buildReadme(
  spec: StudySpec,
  generated: { sas: GeneratedFile[]; postgres: GeneratedFile[]; snowflake: GeneratedFile[] },
  generatedAt: string,
): string {
  const m = spec.meta;
  return `# ${m.title}

Generated by HEOR Studio on ${generatedAt}.

- Spec version: ${m.version}
- Database: ${DB_LABELS[m.database] ?? m.database}
- Study period: ${m.studyPeriod.start} to ${m.studyPeriod.end}
- Index period: ${spec.indexEvent.indexPeriod.start} to ${spec.indexEvent.indexPeriod.end}
- Criteria: ${spec.criteria.length} (applied in order)
- Code lists: ${spec.codeLists.length}

## Bundle contents

- \`spec.json\` — the reviewed study specification (single source of truth)
- \`sas/\` — SAS programs (${generated.sas.length} files)
- \`sql_postgres/\` — PostgreSQL scripts (${generated.postgres.length} files)
- \`sql_snowflake/\` — Snowflake scripts (${generated.snowflake.length} files)
- \`codelists/\` — one CSV per code list (code, description, system, source, verified)
- \`AI_DISCLOSURE.md\` — generative-AI use disclosure and human-review attestation

## HEOR Studio notice

HEOR Studio converts a human-reviewed structured specification into deterministic
SAS and SQL. No language model writes or edits code in this bundle; an LLM (if
used at all) only proposed the specification, which an analyst then reviewed
item by item. HEOR Studio runs entirely in the browser: documents go only to the
LLM endpoint the analyst configures, with the analyst's own key.

Time-window conventions used throughout: the baseline period INCLUDES the
index date and runs backward; the follow-up period EXCLUDES the index date and
runs forward; ICD-9/ICD-10 eras are separated via DXVER.

## Verification disclaimer

Generated code is a starting point, not a validated deliverable. Before use in
any analysis, a qualified analyst must (1) confirm every code list against
current terminologies, (2) test the programs against the site's actual
MarketScan delivery and naming, and (3) review outputs for clinical and
statistical plausibility. Use of MarketScan data requires your own valid
license. MarketScan is a registered trademark of Merative US L.P.; HEOR Studio is
independent and unaffiliated.
`;
}

function buildAiDisclosure(spec: StudySpec, generatedAt: string): string {
  const prov = spec.meta.provenance;
  const totalCriteria = spec.criteria.length;
  const reviewedCriteria = totalCriteria - unreviewedCriteria(spec).length;
  const totalCodes = spec.codeLists.reduce((n, cl) => n + cl.codes.length, 0);
  const verifiedCodes = totalCodes - unverifiedCodeCount(spec);
  const readiness = specReadiness(spec);

  const roleSection =
    prov.method === "llm_extraction"
      ? `A large language model was used to extract the structured study
specification from the source document.

- Model: ${prov.model ?? "not recorded"}
- Extraction timestamp: ${prov.extractedAt ?? "not recorded"}
- Source document: ${prov.sourceDocumentName ?? "not recorded"}

The model's only artifact is the structured specification (\`spec.json\`). It
did not write, edit, or select any statistical code.`
      : `No language model was used to produce this specification; it was
authored manually in HEOR Studio.`;

  return `# Generative AI disclosure

This disclosure follows the spirit of the ELEVATE-GenAI reporting guidance for
generative AI in health economics and outcomes research.

## Role of the AI

${roleSection}

All SAS and SQL in this bundle were generated deterministically from the
reviewed specification by HEOR Studio's emitters. Identical specifications always
yield identical code.

## Human oversight

- Criteria reviewed by an analyst: ${reviewedCriteria} of ${totalCriteria}
- Codes verified by an analyst: ${verifiedCodes} of ${totalCodes}
- Readiness at export: ${
    readiness.ready ? "ready (no open problems)" : `NOT ready — ${readiness.problems.join("; ")}`
  }

HEOR Studio refuses to generate code from a specification with unreviewed or
unmapped criteria; export therefore implies the review states recorded above.

## Attestation

Exported on ${generatedAt} from spec version ${spec.meta.version}. By
distributing this bundle, the reviewing analyst attests that the criterion
review flags and code verification flags in \`spec.json\` reflect their own
item-by-item review.
`;
}

/* ---------- assembly ---------- */

/** Place an emitter file under the given folder without double-prefixing. */
function placePath(folder: string, p: string): string {
  if (p.startsWith(`${folder}/`)) return p;
  const i = p.indexOf("/");
  return `${folder}/${i >= 0 ? p.slice(i + 1) : p}`;
}

/**
 * Runs the emitters and lays out every file in the bundle.
 * Throws if an emitter rejects the spec.
 */
export function planBundle(spec: StudySpec, opts: EmitOptions): BundleEntry[] {
  const generatedAt = new Date().toISOString();
  const sas: GeneratedFile[] = emitSas(spec, opts);
  const postgres: GeneratedFile[] = emitSql(spec, "postgres", opts);
  const snowflake: GeneratedFile[] = emitSql(spec, "snowflake", opts);

  const entries: BundleEntry[] = [
    { path: "README.md", content: buildReadme(spec, { sas, postgres, snowflake }, generatedAt) },
    { path: "AI_DISCLOSURE.md", content: buildAiDisclosure(spec, generatedAt) },
    { path: "spec.json", content: JSON.stringify(spec, null, 2) + "\n" },
  ];
  for (const f of sas) entries.push({ path: placePath("sas", f.path), content: f.content });
  for (const f of postgres)
    entries.push({ path: placePath("sql_postgres", f.path), content: f.content });
  for (const f of snowflake)
    entries.push({ path: placePath("sql_snowflake", f.path), content: f.content });
  for (const cl of spec.codeLists)
    entries.push({ path: `codelists/${cl.id}.csv`, content: codeListCsv(cl) });
  return entries;
}

export async function buildZip(entries: BundleEntry[]): Promise<Blob> {
  const zip = new JSZip();
  for (const e of entries) zip.file(e.path, e.content);
  return zip.generateAsync({ type: "blob" });
}

export function bundleFilename(spec: StudySpec): string {
  const slug =
    spec.meta.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "study";
  return `heor-studio_${slug}_v${spec.meta.version}.zip`;
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/** Plan, zip, and download in one step. */
export async function exportStudyBundle(spec: StudySpec, opts: EmitOptions): Promise<string> {
  const entries = planBundle(spec, opts);
  const blob = await buildZip(entries);
  const name = bundleFilename(spec);
  downloadBlob(blob, name);
  return name;
}
