/*=============================================================================
| HEOR Studio — Gold Case A fixture, as SAS data sets
|
| GENERATED by packages/core/src/verify/sas-fixture.ts. Do not hand-edit: the
| rows are read out of the same PGlite database the harness executes the
| emitted SQL against, so these twelve patients and those twelve patients are
| the same twelve patients by construction.
|
| PURPOSE. The SAS twin has never been executed. Run this first, then run the
| emitted programs 00 through 360 in order, then compare what they print
| against SAS-COMPARISON.md, which carries the values Postgres produced from
| the same rows.
|
| SAS OnDemand for Academics (free) is enough. No MarketScan licence is
| involved: every row below is synthetic and was written by hand to exercise
| a specific rule.
|
| WHAT TO DO WITH A DISAGREEMENT. A difference here is a FINDING, not a
| nuisance. The SQL side is executed against ground truth derived by hand as
| exact fractions before anything ran, so if SAS says something else, either
| the SAS twin is wrong or the derivation is. Both have happened.
=============================================================================*/

/*-- EDIT: point this at a folder you can write to. On SAS OnDemand for
    Academics, /home/<your-user>/heor is a good choice. This must match the
    `raw` libname in the emitted 00_setup.sas. --------------------------*/
%let fixture_out = /home/u00000000/heor;

libname raw "&fixture_out.";

options nocenter;

/*---------------------------------------------------------------------------
  ccaet_all  ->  raw.ccaetYY1   (enrollment detail)
  18 row(s), split by dtstart across 2018-2021.
---------------------------------------------------------------------------*/

data raw.ccaet181;
  length enrolid 8 dtstart 8 dtend 8 rx $20 drugcovg $20 dobyr 8 age 8 sex $20 region $20 plantyp $20 egeoloc $20;
  informat dtstart date9. dtend date9.;
  format dtstart date9. dtend date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid dtstart dtend rx $ drugcovg $ dobyr age sex $ region $ plantyp $ egeoloc $;
datalines;
1|01JAN2018|30JUN2020|1|1|1979|40|1|1|6|1
2|01JAN2018|30JUN2020|1|1|1974|45|2|1|6|1
3|01JAN2018|30JUN2020|1|1|1969|50|1|2|6|1
4|01JAN2018|30JUN2020|1|1|1964|55|2|2|6|1
5|01JAN2018|30JUN2020|1|1|1959|60|1|3|6|1
6|01JAN2018|30JUN2020|1|1|1974|45|1|3|7|1
7|01JAN2018|10JUN2019|1|1|1969|50|2|4|7|1
8|01JAN2018|30JUN2020|1|1|1964|55|1|4|7|1
9|01JAN2018|30JUN2020|1|1|1959|60|2|1|7|1
10|01JAN2018|30JUN2020|1|1|1954|65|1|2|7|1
11|01JAN2018|01MAY2019|1|1|1970|49|2|2|6|1
12|01JAN2018|30JUN2020|1|1|2009|10|1|3|7|1
13|01JAN2018|31MAR2019|1|1|1980|39|2|1|6|1
13|01FEB2018|10FEB2018|1|1|1980|39|2|1|6|1
14|01JAN2018|30JUN2020|1|1|1975|44|1|2|6|1
;
run;

data raw.ccaet191;
  length enrolid 8 dtstart 8 dtend 8 rx $20 drugcovg $20 dobyr 8 age 8 sex $20 region $20 plantyp $20 egeoloc $20;
  informat dtstart date9. dtend date9.;
  format dtstart date9. dtend date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid dtstart dtend rx $ drugcovg $ dobyr age sex $ region $ plantyp $ egeoloc $;
datalines;
7|30JUN2019|30JUN2020|1|1|1969|50|2|4|7|1
11|01JUL2019|30JUN2020|1|1|1970|49|2|2|6|1
13|15APR2019|30JUN2020|1|1|1980|39|2|1|6|1
;
run;

data raw.ccaet201;
  length enrolid 8 dtstart 8 dtend 8 rx $20 drugcovg $20 dobyr 8 age 8 sex $20 region $20 plantyp $20 egeoloc $20;
  informat dtstart date9. dtend date9.;
  format dtstart date9. dtend date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid dtstart dtend rx $ drugcovg $ dobyr age sex $ region $ plantyp $ egeoloc $;
datalines;
;
run;
/* EMPTY BY DESIGN. enrollment detail has no 2020 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaet211;
  length enrolid 8 dtstart 8 dtend 8 rx $20 drugcovg $20 dobyr 8 age 8 sex $20 region $20 plantyp $20 egeoloc $20;
  informat dtstart date9. dtend date9.;
  format dtstart date9. dtend date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid dtstart dtend rx $ drugcovg $ dobyr age sex $ region $ plantyp $ egeoloc $;
datalines;
;
run;
/* EMPTY BY DESIGN. enrollment detail has no 2021 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

/*---------------------------------------------------------------------------
  ccaed_all  ->  raw.ccaedYY1   (outpatient pharmacy claims)
  13 row(s), split by svcdate across 2018-2021.
---------------------------------------------------------------------------*/

data raw.ccaed181;
  length enrolid 8 svcdate 8 ndcnum $20 daysupp 8 qty 8 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate ndcnum $ daysupp qty paytot netpay copay deduct coins;
datalines;
;
run;
/* EMPTY BY DESIGN. outpatient pharmacy claims has no 2018 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaed191;
  length enrolid 8 svcdate 8 ndcnum $20 daysupp 8 qty 8 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate ndcnum $ daysupp qty paytot netpay copay deduct coins;
datalines;
1|01JAN2019|00000000001|30|30|100|.|.|.|.
2|01JAN2019|00000000001|30|30|100|.|.|.|.
3|01JAN2019|00000000001|30|30|100|.|.|.|.
4|01JAN2019|00000000001|30|30|100|.|.|.|.
5|01JAN2019|00000000001|30|30|100|.|.|.|.
11|01JAN2019|00000000001|30|30|100|.|.|.|.
6|01JAN2019|00000000002|30|30|100|.|.|.|.
7|01JAN2019|00000000002|30|30|100|.|.|.|.
8|01JAN2019|00000000002|30|30|100|.|.|.|.
9|01JAN2019|00000000002|30|30|100|.|.|.|.
10|01JAN2019|00000000002|30|30|100|.|.|.|.
12|01JAN2019|00000000002|30|30|100|.|.|.|.
3|01FEB2019|99999999999|30|30|100|.|.|.|.
;
run;

data raw.ccaed201;
  length enrolid 8 svcdate 8 ndcnum $20 daysupp 8 qty 8 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate ndcnum $ daysupp qty paytot netpay copay deduct coins;
datalines;
;
run;
/* EMPTY BY DESIGN. outpatient pharmacy claims has no 2020 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaed211;
  length enrolid 8 svcdate 8 ndcnum $20 daysupp 8 qty 8 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate ndcnum $ daysupp qty paytot netpay copay deduct coins;
datalines;
;
run;
/* EMPTY BY DESIGN. outpatient pharmacy claims has no 2021 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

/*---------------------------------------------------------------------------
  ccaeo_all  ->  raw.ccaeoYY1   (outpatient services)
  17 row(s), split by svcdate across 2018-2021.
---------------------------------------------------------------------------*/

data raw.ccaeo181;
  length enrolid 8 svcdate 8 dxver $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 proc1 $20 proctyp $20 stdplac $20 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate dxver $ dx1 $ dx2 $ dx3 $ dx4 $ proc1 $ proctyp $ stdplac $ paytot netpay copay deduct coins;
datalines;
1|01JUN2018|0|E119|.|.|.|.|.|11|200|.|.|.|.
6|01SEP2018|0|E119|.|.|.|.|.|11|200|.|.|.|.
1|15JUN2018|0|I500|.|.|.|.|.|11|200|.|.|.|.
2|15JUN2018|0|E100|.|.|.|.|.|11|200|.|.|.|.
3|15JUN2018|0|E100|.|.|.|.|.|11|200|.|.|.|.
3|15JUN2018|0|E102|.|.|.|.|.|11|200|.|.|.|.
4|15JUN2018|0|K703|.|.|.|.|.|11|200|.|.|.|.
5|15JUN2018|0|K703|.|.|.|.|.|11|200|.|.|.|.
5|15JUN2018|0|K721|.|.|.|.|.|11|200|.|.|.|.
6|15JUN2018|0|I500|.|.|.|.|.|11|200|.|.|.|.
6|15JUN2018|0|E102|.|.|.|.|.|11|200|.|.|.|.
;
run;

data raw.ccaeo191;
  length enrolid 8 svcdate 8 dxver $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 proc1 $20 proctyp $20 stdplac $20 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate dxver $ dx1 $ dx2 $ dx3 $ dx4 $ proc1 $ proctyp $ stdplac $ paytot netpay copay deduct coins;
datalines;
2|11APR2019|0|E119|.|.|.|.|.|11|200|.|.|.|.
3|20JUL2019|0|E119|.|.|.|.|.|11|200|.|.|.|.
7|28OCT2019|0|E119|.|.|.|.|.|11|200|.|.|.|.
2|01MAY2019|0|Z0000|.|.|.|.|.|11|200|.|.|.|.
2|15MAY2019|0|Z0000|.|.|.|.|.|11|200|.|.|.|.
8|10JUN2019|0|Z0000|.|.|.|.|.|23|1500|.|.|.|.
;
run;

data raw.ccaeo201;
  length enrolid 8 svcdate 8 dxver $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 proc1 $20 proctyp $20 stdplac $20 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate dxver $ dx1 $ dx2 $ dx3 $ dx4 $ proc1 $ proctyp $ stdplac $ paytot netpay copay deduct coins;
datalines;
;
run;
/* EMPTY BY DESIGN. outpatient services has no 2020 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaeo211;
  length enrolid 8 svcdate 8 dxver $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 proc1 $20 proctyp $20 stdplac $20 paytot 8 netpay 8 copay 8 deduct 8 coins 8;
  informat svcdate date9.;
  format svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid svcdate dxver $ dx1 $ dx2 $ dx3 $ dx4 $ proc1 $ proctyp $ stdplac $ paytot netpay copay deduct coins;
datalines;
;
run;
/* EMPTY BY DESIGN. outpatient services has no 2021 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

/*---------------------------------------------------------------------------
  ccaes_all  ->  raw.ccaesYY1   (inpatient services)
  4 row(s), split by svcdate across 2018-2021.
---------------------------------------------------------------------------*/

data raw.ccaes181;
  length enrolid 8 admdate 8 svcdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 pproc $20 proc1 $20 proctyp $20 caseid 8 paytot 8 netpay 8;
  informat admdate date9. svcdate date9.;
  format admdate date9. svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate svcdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ pproc $ proc1 $ proctyp $ caseid paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient services has no 2018 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaes191;
  length enrolid 8 admdate 8 svcdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 pproc $20 proc1 $20 proctyp $20 caseid 8 paytot 8 netpay 8;
  informat admdate date9. svcdate date9.;
  format admdate date9. svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate svcdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ pproc $ proc1 $ proctyp $ caseid paytot netpay;
datalines;
5|01MAR2019|01MAR2019|0|E119|.|.|.|.|.|.|.|.|5000|.
14|01MAY2019|04MAY2019|0|E119|.|.|.|.|.|.|.|14001|2000|.
4|01AUG2019|01AUG2019|0|Z0000|.|.|.|.|.|.|.|4001|3000|.
4|01AUG2019|03AUG2019|0|Z0000|.|.|.|.|.|.|.|4001|4000|.
;
run;

data raw.ccaes201;
  length enrolid 8 admdate 8 svcdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 pproc $20 proc1 $20 proctyp $20 caseid 8 paytot 8 netpay 8;
  informat admdate date9. svcdate date9.;
  format admdate date9. svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate svcdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ pproc $ proc1 $ proctyp $ caseid paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient services has no 2020 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaes211;
  length enrolid 8 admdate 8 svcdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 pproc $20 proc1 $20 proctyp $20 caseid 8 paytot 8 netpay 8;
  informat admdate date9. svcdate date9.;
  format admdate date9. svcdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate svcdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ pproc $ proc1 $ proctyp $ caseid paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient services has no 2021 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

/*---------------------------------------------------------------------------
  ccaei_all  ->  raw.ccaeiYY1   (inpatient admissions)
  2 row(s), split by admdate across 2018-2021.
---------------------------------------------------------------------------*/

data raw.ccaei181;
  length enrolid 8 admdate 8 disdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 dx5 $20 dx6 $20 dx7 $20 dx8 $20 dx9 $20 dx10 $20 dx11 $20 dx12 $20 dx13 $20 dx14 $20 dx15 $20 pproc $20 proc1 $20 proc2 $20 proc3 $20 proc4 $20 proc5 $20 proc6 $20 proc7 $20 proc8 $20 proc9 $20 proc10 $20 proc11 $20 proc12 $20 proc13 $20 proc14 $20 proc15 $20 caseid 8 los 8 paytot 8 netpay 8;
  informat admdate date9. disdate date9.;
  format admdate date9. disdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate disdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ dx5 $ dx6 $ dx7 $ dx8 $ dx9 $ dx10 $ dx11 $ dx12 $ dx13 $ dx14 $ dx15 $ pproc $ proc1 $ proc2 $ proc3 $ proc4 $ proc5 $ proc6 $ proc7 $ proc8 $ proc9 $ proc10 $ proc11 $ proc12 $ proc13 $ proc14 $ proc15 $ caseid los paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient admissions has no 2018 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaei191;
  length enrolid 8 admdate 8 disdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 dx5 $20 dx6 $20 dx7 $20 dx8 $20 dx9 $20 dx10 $20 dx11 $20 dx12 $20 dx13 $20 dx14 $20 dx15 $20 pproc $20 proc1 $20 proc2 $20 proc3 $20 proc4 $20 proc5 $20 proc6 $20 proc7 $20 proc8 $20 proc9 $20 proc10 $20 proc11 $20 proc12 $20 proc13 $20 proc14 $20 proc15 $20 caseid 8 los 8 paytot 8 netpay 8;
  informat admdate date9. disdate date9.;
  format admdate date9. disdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate disdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ dx5 $ dx6 $ dx7 $ dx8 $ dx9 $ dx10 $ dx11 $ dx12 $ dx13 $ dx14 $ dx15 $ pproc $ proc1 $ proc2 $ proc3 $ proc4 $ proc5 $ proc6 $ proc7 $ proc8 $ proc9 $ proc10 $ proc11 $ proc12 $ proc13 $ proc14 $ proc15 $ caseid los paytot netpay;
datalines;
14|01MAY2019|06MAY2019|0|E119|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|14001|.|8000|.
4|01AUG2019|05AUG2019|0|Z0000|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|4001|.|10000|.
;
run;

data raw.ccaei201;
  length enrolid 8 admdate 8 disdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 dx5 $20 dx6 $20 dx7 $20 dx8 $20 dx9 $20 dx10 $20 dx11 $20 dx12 $20 dx13 $20 dx14 $20 dx15 $20 pproc $20 proc1 $20 proc2 $20 proc3 $20 proc4 $20 proc5 $20 proc6 $20 proc7 $20 proc8 $20 proc9 $20 proc10 $20 proc11 $20 proc12 $20 proc13 $20 proc14 $20 proc15 $20 caseid 8 los 8 paytot 8 netpay 8;
  informat admdate date9. disdate date9.;
  format admdate date9. disdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate disdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ dx5 $ dx6 $ dx7 $ dx8 $ dx9 $ dx10 $ dx11 $ dx12 $ dx13 $ dx14 $ dx15 $ pproc $ proc1 $ proc2 $ proc3 $ proc4 $ proc5 $ proc6 $ proc7 $ proc8 $ proc9 $ proc10 $ proc11 $ proc12 $ proc13 $ proc14 $ proc15 $ caseid los paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient admissions has no 2020 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

data raw.ccaei211;
  length enrolid 8 admdate 8 disdate 8 dxver $20 pdx $20 dx1 $20 dx2 $20 dx3 $20 dx4 $20 dx5 $20 dx6 $20 dx7 $20 dx8 $20 dx9 $20 dx10 $20 dx11 $20 dx12 $20 dx13 $20 dx14 $20 dx15 $20 pproc $20 proc1 $20 proc2 $20 proc3 $20 proc4 $20 proc5 $20 proc6 $20 proc7 $20 proc8 $20 proc9 $20 proc10 $20 proc11 $20 proc12 $20 proc13 $20 proc14 $20 proc15 $20 caseid 8 los 8 paytot 8 netpay 8;
  informat admdate date9. disdate date9.;
  format admdate date9. disdate date9.;
  infile datalines dlm='|' dsd missover;
  input enrolid admdate disdate dxver $ pdx $ dx1 $ dx2 $ dx3 $ dx4 $ dx5 $ dx6 $ dx7 $ dx8 $ dx9 $ dx10 $ dx11 $ dx12 $ dx13 $ dx14 $ dx15 $ pproc $ proc1 $ proc2 $ proc3 $ proc4 $ proc5 $ proc6 $ proc7 $ proc8 $ proc9 $ proc10 $ proc11 $ proc12 $ proc13 $ proc14 $ proc15 $ caseid los paytot netpay;
datalines;
;
run;
/* EMPTY BY DESIGN. inpatient admissions has no 2021 rows. The data set still has to
   exist: the twin's %do yr loop appends every year in the range, and
   proc append against a base that is not there is a hard error. */

/*---------------------------------------------------------------------------
  redbook -> raw.redbook   (NDC reference; 2 rows, not year-split)
---------------------------------------------------------------------------*/
data raw.redbook;
  length ndcnum $40 gennme $40 prodnme $40;
  infile datalines dlm='|' dsd missover;
  input ndcnum $ gennme $ prodnme $;
datalines;
00000000001|DRUG_X|BRAND_X
00000000002|DRUG_Y|BRAND_Y
;
run;

/*-------------------- what landed ------------------------------------------*/
title 'Fixture load: row counts by data set';
proc sql;
  select memname, nobs from dictionary.tables
  where libname = 'RAW' order by memname;
quit;
title;

/* NEXT: set `libname raw` in the emitted 00_setup.sas to &fixture_out., leave
   %let prefix = ccae and %let rel = 1 as they are, then run 00 through 360 in
   order. Compare against SAS-COMPARISON.md. */
